#include "params.h"

const int PARAM_QMAX = 32;
const int PARAM_NULL_DEPTH = 2;
const int PARAM_LMR_DEPTH = 4;
const int PARAM_LMR_MOVES = 4;
const int PARAM_PAWN_STRUCTURE_WEIGHT = 1;
const int PARAM_KING_SAFETY_WEIGHT = 2;
const int PARAM_ROOK_ACTIVITY_WEIGHT = 1;
const int PARAM_BISHOP_PAIR_BONUS = 30;
const int PARAM_KING_ATTACK_SCALE = 4;
const int PARAM_ATTACK_WEIGHT_PAWN = 1;
const int PARAM_ATTACK_WEIGHT_MINOR = 3;
const int PARAM_ATTACK_WEIGHT_ROOK = 4;
const int PARAM_ATTACK_WEIGHT_QUEEN = 6;
const int PARAM_HANGING_PENALTY_PCT = 70;
const int PARAM_TEMPO_BONUS = 8;
const int PARAM_MOBILITY_WEIGHT = 5;
const int PARAM_KING_ATTACK_WEIGHT = 5;
const int PARAM_DEFAULT_SEARCH_DEPTH = 52;
const int PARAM_DEFAULT_MOVE_TIME_MS = 10000;
const int PARAM_MOVE_TIME_INCREMENT_MS = 0;
const int PARAM_TT_CLEAR_ON_NEW_SEARCH = 0;
const int PARAM_TT_LOAD_ON_START = 1;
const int PARAM_TT_SAVE_ON_EXIT = 1;
const char *PARAM_TT_CACHE_PATH = "tt_cache.bin";
